// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import io.nats.client.*;
import io.nats.client.api.*;
import io.nats.client.impl.ErrorListenerLoggerImpl;

public class Connect extends CustomJavaAction<java.lang.String>
{
	public Connect(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		ErrorListener el = new ErrorListenerLoggerImpl() {
			@Override
			public void flowControlProcessed(Connection conn, JetStreamSubscription sub, String id, FlowControlSource source) {
				// do nothing. flow control happens during downloads, it's just an info, not a warning.
			}
		};

		String SERVER = "nats://localhost:4222";

		Options options = new Options.Builder()
			.server(SERVER)
			.errorListener(el)
			.build();

		try (Connection conn = Nats.connect(options)) {
			ServerInfo si = conn.getServerInfo();
			System.out.println(si);
			return si.toString();
		}
		catch (Exception e) {
			e.printStackTrace();
		}

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Connect";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
